# Generated by Django 3.0.2 on 2020-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[(1, 'open'), (2, 'close')], max_length=1)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
